name: momenta_share
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.0.5
  intl: ^0.19.0
  provider: ^6.1.1
  timeago: ^3.2.2
  uuid: ^4.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: OleoScript
      fonts:
        - asset: assets/fonts/OleoScript-Regular.ttf
        - asset: assets/fonts/OleoScript-Bold.ttf
          weight: 700

    - family: Kalnia
      fonts:
        - asset: assets/fonts/Kalnia-Regular.ttf
        - asset: assets/fonts/Kalnia-Bold.ttf
          weight: 700
